In [1]:
import pandas as pd
import os
import glob

In [2]:

path = os.getcwd()
csv_files = glob.glob(os.path.join(path + '/ejecucion/', "*.csv"))
#csv_files = [csv_files[4]]
csv_files

['/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/ejecucion/2020.csv',
 '/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/ejecucion/2021.csv',
 '/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/ejecucion/2022.csv',
 '/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/ejecucion/2019.csv',
 '/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/ejecucion/2018.csv',
 '/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/ejecucion/2017.csv']

In [3]:
dfejecucion = pd.DataFrame()
for f in csv_files:
    df = pd.read_csv(f, sep=';', thousands='.')
    dfejecucion = pd.concat([dfejecucion, df], axis=0)

dfejecucion.reset_index(drop=True, inplace=True)
dfejecucion.columns = ['Ano', 'Mes', 'Moneda', 'Partida', 'Nombre Partida', 'Capitulo', 'Nombre Capitulo', 'Programa', 'Nombre Programa', 'Subtitulo', 'Nombre Subtitulo', 'Item', 'Nombre Item','Asignacion', 'Nombre Asignacion', 'Sub-Asignación', 'Nombre Sub-Asignación', 'Ejecución de AGOSTO', 'Ejecución a AGOSTO']

In [4]:
dfejecucion['Item'].fillna(0, inplace=True)
dfejecucion['Asignacion'].fillna(0, inplace=True)
dfejecucion['Sub-Asignación'].fillna(0, inplace=True)
dfejecucion.sort_values(by=['Partida','Capitulo','Programa','Subtitulo','Item','Asignacion', 'Sub-Asignación'], inplace=True)

In [5]:
dftemp = dfejecucion[((dfejecucion['Subtitulo']==24)&(dfejecucion['Item']==2))]
dfejecucion = dfejecucion.merge(dftemp, how='outer', indicator=True)
dfejecucion = dfejecucion[dfejecucion['_merge']=='left_only']
dfejecucion.drop('_merge', inplace = True, axis=1)

dftemp = dfejecucion[((dfejecucion['Subtitulo']==33)&(dfejecucion['Item']==2))]
dfejecucion = dfejecucion.merge(dftemp, how='outer', indicator=True)
dfejecucion = dfejecucion[dfejecucion['_merge']=='left_only']
dfejecucion.drop('_merge', inplace = True, axis=1)

In [6]:
dfejec_acum = dfejecucion.groupby(by=['Ano','Mes','Moneda','Partida','Nombre Partida','Capitulo','Nombre Capitulo','Programa','Nombre Programa','Subtitulo','Nombre Subtitulo','Item','Nombre Item','Asignacion','Nombre Asignacion'])['Ejecución a AGOSTO'].sum()
dfejec_acum = dfejec_acum.reset_index()

In [7]:
dfejec_acum['Ejecucion a Agosto en Pesos'] = dfejec_acum['Ejecución a AGOSTO']
dolares = [[2017,648],[2018,641],[2019,703],[2020,792],[2021,759],[2022, 859]]

for año, dolar in dolares:
    dfejec_acum.loc[(dfejec_acum['Ano'] == año)&(dfejec_acum['Moneda']=='DOLARES'), 'Ejecucion a Agosto en Pesos'] = dfejec_acum['Ejecución a AGOSTO'] * dolar

dfejec_acum

,Ano,Mes,Moneda,Partida,Nombre Partida,Capitulo,Nombre Capitulo,Programa,Nombre Programa,Subtitulo,Nombre Subtitulo,Item,Nombre Item,Asignacion,Nombre Asignacion,Ejecución a AGOSTO,Ejecucion a Agosto en Pesos
0,2017,Agosto,DOLARES,5,MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA,31,CARABINEROS DE CHILE,1,CARABINEROS DE CHILE,9,APORTE FISCAL,1,Libre,1,Remuneraciones,3286,2129328
1,2017,Agosto,DOLARES,5,MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA,31,CARABINEROS DE CHILE,1,CARABINEROS DE CHILE,9,APORTE FISCAL,1,Libre,2,Resto,29256,18957888
2,2017,Agosto,DOLARES,5,MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA,31,CARABINEROS DE CHILE,1,CARABINEROS DE CHILE,11,VENTA DE ACTIVOS FINANCIEROS,3,Operaciones de Cambio,2,Gastos por Operaciones de Cambio,-11523,-7466904
3,2017,Agosto,DOLARES,5,MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA,31,CARABINEROS DE CHILE,1,CARABINEROS DE CHILE,21,GASTOS EN PERSONAL,1,Personal de Planta,1,Sueldos y Sobresueldos,2920,1892160
4,2017,Agosto,DOLARES,5,MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA,31,CARABINEROS DE CHILE,1,CARABINEROS DE CHILE,21,GASTOS EN PERSONAL,1,Personal de Planta,4,Remuneraciones Variables,654,423792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124680,2022,Agosto,PESOS,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,24,TRANSFERENCIAS CORRIENTES,4,A Empresas Públicas no Financieras,4,Sociedad Agrícola y Servicios Isla de Pascua SpA,1463150,1463150
124681,2022,Agosto,PESOS,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,30,ADQUISICIÓN DE ACTIVOS FINANCIEROS,1,Compra de Títulos y Valores,999,Otros,31859779,31859779
124682,2022,Agosto,PESOS,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,30,ADQUISICIÓN DE ACTIVOS FINANCIEROS,2,Compra de Acciones y Participaciones de Capital,4,Fondo de Infraestructura S.A.,1074615,1074615
124683,2022,Agosto,PESOS,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,30,ADQUISICIÓN DE ACTIVOS FINANCIEROS,2,Compra de Acciones y Participaciones de Capital,5,Empresa de Transporte de Pasajeros Metro S.A.,73500000,73500000
124684,2022,Agosto,PESOS,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,33,TRANSFERENCIAS DE CAPITAL,4,A Empresas Públicas no Financieras,2,Sociedad Agrícola y Servicios Isla de Pascua SpA,28393621,28393621

In [8]:
csv_files = glob.glob(os.path.join(path + '/PV/', "*.csv"))

In [9]:
dffinal = pd.DataFrame()
for f in csv_files:
    print(f)
    if f.rfind('PV2018.csv')>0:
        df = pd.read_csv(f, sep='\t', thousands=r'.')
        df.drop(columns=df.columns[-1:], axis=1,  inplace=True)

    elif f.rfind('PV2022.csv')>0:
        df = pd.read_csv(f, sep=',', thousands=r'.')
        df.drop('_id', axis=1, inplace=True)

    else:
        df = pd.read_csv(f, sep=';', thousands=r'.')
    
    df.columns = ['Ano','Mes','Moneda','Partida','Nombre Partida','Capitulo','Nombre Capitulo','Programa','Nombre Programa','Subtitulo','Nombre Subtitulo','Item','Nombre Item','Asignacion','Nombre Asignacion'\
        ,'Monto Ley Inicial','Monto Ley Vigente a AGOSTO']
    df['Item'].fillna(0, inplace=True)
    df['Asignacion'].fillna(0, inplace=True)
    df = df.sort_values(by=['Partida','Capitulo','Programa','Subtitulo','Item','Asignacion'])
    #df = df[(df['Partida']==6)&(df['Capitulo']==1)]
    #df = df[(df['Partida']==50)]#&(df['Subtitulo']==1)]#&(df['Programa']==1)]
    PCP = df[['Partida','Capitulo','Programa']].drop_duplicates()
    df_total = pd.DataFrame()
    for i, row in PCP.iterrows():
        df_temp = df[(df['Partida']==row['Partida'])&(df['Capitulo']==row['Capitulo'])&(df['Programa']==row['Programa'])]
        subtitulos = df_temp.Subtitulo.unique()
        df_prog = pd.DataFrame()
        monedas = df_temp.Moneda.unique()
        for moneda in monedas:
            df_mon = df_temp[df_temp['Moneda']==moneda]
            for subt in subtitulos:
                df_subt = df_mon[df_mon['Subtitulo']==subt]
                if len(df_subt) > 1:
                    df_subt_ceros = df_mon[df_mon['Subtitulo']==subt]
                    df_subt_ceros = df_subt_ceros[(df_subt_ceros['Asignacion']==0)&(df_subt_ceros['Item']==0)]
                    if len(df_subt_ceros) ==0:
                        df_subt_suma = df_subt.groupby('Subtitulo')['Monto Ley Vigente a AGOSTO'].sum().values[0]
                    else:
                        df_subt_suma = df_subt_ceros.groupby('Subtitulo')['Monto Ley Vigente a AGOSTO'].sum().values[0]

                    if len(df_subt[df_subt['Item']!=0]) == 0:
                        df_subt = df_subt.copy()
                    else:
                        df_subt = df_subt[df_subt['Item']!=0]
                    items = df_subt.Item.unique()
                    df_item_to = pd.DataFrame()
                    for item in items:
                        df_item = df_subt[df_subt['Item']==item]
                        #display(df_item)
                        #print(len(df_item))
                        if len(df_item) > 1:
                            if len(df_item[df_item['Asignacion']!=0]) == 0:
                                if len(df_item[df_item['Item']!=0])==0:
                                    df_item2 = df_item.copy()
                                else:
                                    df_item2 = df_item[df_item['Item']!=0]
                            else:
                                df_item2 = df_item[df_item['Asignacion']!=0]
                                try: 
                                    #print(df_item2.groupby('Item')['Monto Ley Vigente a AGOSTO'].sum().values[0], df_item.reset_index(drop=True)[:1]['Monto Ley Vigente a AGOSTO'].values[0])
                                    if df_item2.groupby('Item')['Monto Ley Vigente a AGOSTO'].sum().values[0] == df_item.reset_index(drop=True)[:1]['Monto Ley Vigente a AGOSTO'].values[0]:
                                        #print('1')
                                        df_item = df_item2.copy()
                                    else:
                                        #print(2)
                                        df_item.reset_index(drop=True, inplace=True)
                                        df_item.at[0, 'Asignacion'] = 9999
                                        df_item.at[0, 'Monto Ley Vigente a AGOSTO'] = df_item.reset_index(drop=True)[:1]['Monto Ley Vigente a AGOSTO'].values[0] - df_item2.groupby('Item')['Monto Ley Vigente a AGOSTO'].sum().values[0]
                                except:
                                    df_item = df_item[df_item['Asignacion']!=0]

                        #display(df_item)
                        
                        df_item_to = pd.concat([df_item, df_item_to], axis=0)

                    precalculo_subt = df_item_to.groupby('Subtitulo')['Monto Ley Vigente a AGOSTO'].sum().values[0]

                    if df_subt_suma != precalculo_subt:
                        df_subt_ceros.reset_index(drop=True, inplace=True)
                        df_subt_ceros.at[0, 'Asignacion'] = 9999
                        df_subt_ceros.at[0, 'Monto Ley Vigente a AGOSTO'] = df_subt_suma - precalculo_subt
                        df_item_to = pd.concat([df_subt_ceros, df_item_to], axis=0)
                        df_item_to.reset_index(drop=True, inplace=True)

                    df_prog = pd.concat([df_item_to, df_prog], axis=0)
                else:
                    df_prog = pd.concat([df_subt, df_prog], axis=0)

            df_total = pd.concat([df_prog, df_total], axis=0)

    df_total = df_total.sort_values(by=['Partida','Capitulo','Programa','Subtitulo','Item','Asignacion'])
    df_total.drop_duplicates(inplace=True)
    dffinal = pd.concat([df_total, dffinal], axis=0)

/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/PV/PV2017.csv
/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/PV/PV2019.csv
/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/PV/PV2018.csv
/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/PV/PV2022.csv
/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/PV/PV2020.csv
/Users/josemora/Documents/Github/Scrapers/Presupuesto 2023/PV/PV2021.csv

In [23]:
dfpresu = dffinal.copy()
dfpresu['Ppto Vigente a Agosto en Pesos'] = dfpresu['Monto Ley Vigente a AGOSTO']
dfpresu = dfpresu.reset_index(drop=True)
for año, dolar in dolares:
    dfpresu.loc[(dfpresu['Ano'] == año)&(dfpresu['Moneda']=='DOLARES'), 'Ppto Vigente a Agosto en Pesos'] = dfpresu['Monto Ley Vigente a AGOSTO'] * dolar

In [25]:
dftemp = dfpresu[((dfpresu['Subtitulo']==24)&(dfpresu['Item']==2))]
dfpresu = dfpresu.merge(dftemp, how='outer', indicator=True)
dfpresu = dfpresu[dfpresu['_merge']=='left_only']
dfpresu.drop('_merge', inplace = True, axis=1)

dftemp = dfpresu[((dfpresu['Subtitulo']==33)&(dfpresu['Item']==2))]
dfpresu = dfpresu.merge(dftemp, how='outer', indicator=True)
dfpresu = dfpresu[dfpresu['_merge']=='left_only']
dfpresu.drop('_merge', inplace = True, axis=1)
dftemp

Empty DataFrame
Columns: [Ano, Mes, Moneda, Partida, Nombre Partida, Capitulo, Nombre Capitulo, Programa, Nombre Programa, Subtitulo, Nombre Subtitulo, Item, Nombre Item, Asignacion, Nombre Asignacion, Monto Ley Inicial, Monto Ley Vigente a AGOSTO, Ppto Vigente a Agosto en Pesos]
Index: []

In [12]:
dfpresu

Empty DataFrame
Columns: [Ano, Mes, Moneda, Partida, Nombre Partida, Capitulo, Nombre Capitulo, Programa, Nombre Programa, Subtitulo, Nombre Subtitulo, Item, Nombre Item, Asignacion, Nombre Asignacion, Monto Ley Inicial, Monto Ley Vigente a AGOSTO, Ppto Vigente a Agosto en Pesos]
Index: []

In [13]:
dfpresu_subt = dfpresu.groupby(['Ano','Partida','Nombre Partida','Capitulo','Nombre Capitulo','Programa','Nombre Programa','Subtitulo','Nombre Subtitulo'])['Ppto Vigente a Agosto en Pesos'].sum()
dfpresu_subt = dfpresu_subt.reset_index()

dfejec_subt = dfejec_acum.groupby(['Ano','Partida','Nombre Partida','Capitulo','Nombre Capitulo','Programa','Nombre Programa','Subtitulo','Nombre Subtitulo'])['Ejecucion a Agosto en Pesos'].sum()
dfejec_subt = dfejec_subt.reset_index()

In [14]:
df_avance_ejec = dfpresu_subt.merge(dfejec_subt, how='outer', on=['Ano','Partida','Capitulo','Programa', 'Subtitulo'], indicator=True)
df_avance_ejec

,Nombre Partida_x,Nombre Capitulo_x,Nombre Programa_x,Nombre Subtitulo_x,Ppto Vigente a Agosto en Pesos,Ano,Partida,Nombre Partida_y,Capitulo,Nombre Capitulo_y,Programa,Nombre Programa_y,Subtitulo,Nombre Subtitulo_y,Ejecucion a Agosto en Pesos,_merge
0,NaN,NaN,NaN,NaN,NaN,2017,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,8,OTROS INGRESOS CORRIENTES,304314,right_only
1,NaN,NaN,NaN,NaN,NaN,2017,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,9,APORTE FISCAL,12282862,right_only
2,NaN,NaN,NaN,NaN,NaN,2017,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,12,RECUPERACIÓN DE PRÉSTAMOS,205662,right_only
3,NaN,NaN,NaN,NaN,NaN,2017,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,21,GASTOS EN PERSONAL,4697652,right_only
4,NaN,NaN,NaN,NaN,NaN,2017,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,1,PRESIDENCIA DE LA REPÚBLICA,22,BIENES Y SERVICIOS DE CONSUMO,4124087,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16976,NaN,NaN,NaN,NaN,NaN,2022,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,5,TRANSFERENCIAS CORRIENTES,63837619,right_only
16977,NaN,NaN,NaN,NaN,NaN,2022,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,13,TRANSFERENCIAS PARA GASTOS DE CAPITAL,134828015,right_only
16978,NaN,NaN,NaN,NaN,NaN,2022,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,24,TRANSFERENCIAS CORRIENTES,63837619,right_only
16979,NaN,NaN,NaN,NaN,NaN,2022,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,30,ADQUISICIÓN DE ACTIVOS FINANCIEROS,106434394,right_only
16980,NaN,NaN,NaN,NaN,NaN,2022,50,TESORO PÚBLICO,1,FISCO,11,EMPRESAS Y SOCIEDADES DEL ESTADO,33,TRANSFERENCIAS DE CAPITAL,28393621,right_only

In [15]:
df_avance_ejec.to_excel('output/niveldeejecucion.xlsx')

In [16]:
dfanaliticos = pd.read_excel('output/analiticos.xlsx', sheet_name='DATOSEXTRASFINALES')
dftemp = dfanaliticos[((dfanaliticos['subtitulo']==24)&(dfanaliticos['item']==2))]
dfanaliticos = dfanaliticos.merge(dftemp, how='outer', indicator=True)
dfanaliticos = dfanaliticos[dfanaliticos['_merge']=='left_only']
dfanaliticos.drop('_merge', inplace = True, axis=1)

dftemp = dfanaliticos[((dfanaliticos['subtitulo']==33)&(dfanaliticos['item']==2))]
dfanaliticos = dfanaliticos.merge(dftemp, how='outer', indicator=True)
dfanaliticos = dfanaliticos[dfanaliticos['_merge']=='left_only']
dfanaliticos.drop('_merge', inplace = True, axis=1)

dfanaliticos = dfanaliticos[dfanaliticos['capitulo'] != '20-53']

In [17]:
dfanali_subt = dfanaliticos.groupby(['subtitulo','n_subtitulo','moneda',
       'partida', 'n_partida', 'capitulo', 'n_capitulo','programa', 'n_programa'])['VARIACIÓN Monto $ (5) - (4) CALCULADA', 'AÑO 2022 LEY DE PPTOS (Inicial+Reaj.+Leyes Especiales) (En $ de 2023) (CALCULADO)'].sum()
dfanali_subt = dfanali_subt.reset_index()
dfanali_subt.rename(columns={'subtitulo':'Subtitulo', 'n_subtitulo':'Nombre Subtitulo', 'moneda': 'Moneda', 'partida':'Partida', 'n_partida':'Nombre Partida','capitulo':'Capitulo', 'n_capitulo':'Nombre Capitulo', 'programa':'Programa', 'n_programa':'Nombre Programa','VARIACIÓN Monto $ (5) - (4) CALCULADA':'Variacion 2023 - 2022', 'AÑO 2022 LEY DE PPTOS (Inicial+Reaj.+Leyes Especiales) (En $ de 2023) (CALCULADO)':'Año 2022'}, inplace=True)

/Users/josemora/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

In [18]:
dfanali_subt.to_excel('output/analitico_subtitulos.xlsx')

In [19]:
dfanali_subt[(dfanali_subt['Capitulo'] == '20-53')]

Empty DataFrame
Columns: [Subtitulo, Nombre Subtitulo, Moneda, Partida, Nombre Partida, Capitulo, Nombre Capitulo, Programa, Nombre Programa, Variacion 2023 - 2022, Año 2022]
Index: []